# Generated by Django 4.2 on 2024-08-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search',
            field=models.IntegerField(default=0),
        ),
    ]
