# Generated by Django 4.2 on 2024-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
